[package]
edition = "2024"
name = "analog3"
version = "0.1.0"
license = "MIT"
publish = false

[dependencies]
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "26ad6ec71de3d55e5cbc04a72d7174185f3e86ab", default-features = false, features = [
  "defmt",
  "time-driver-any",
  "memory-x",
  "unstable-pac",
  "exti",
  "chrono",
] }
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git", rev = "26ad6ec71de3d55e5cbc04a72d7174185f3e86ab", features = [
  "defmt",
] }
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "26ad6ec71de3d55e5cbc04a72d7174185f3e86ab", features = [
  "platform-cortex-m",
  "executor-thread",
  "defmt",
] }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "26ad6ec71de3d55e5cbc04a72d7174185f3e86ab", features = [
  "defmt",
  "defmt-timestamp-uptime",
  "tick-hz-32_768",
] }
embassy-futures = { git = "https://github.com/embassy-rs/embassy.git", rev = "26ad6ec71de3d55e5cbc04a72d7174185f3e86ab" }
defmt = "1.0.1"
defmt-rtt = "1.0.0"

cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
embedded-hal = "0.2.6"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
heapless = { version = "0.9", default-features = false }
chrono = { version = "^0.4", default-features = false }
embedded-can = "0.4.1"
defmt-test = "0.4.0"
embedded-storage = "0.3.1"

[profile.release]
debug = 2
opt-level = "s"
lto = true

[package.metadata.embassy]
build = [{ target = "thumbv6m-none-eabi", artifact-dir = "out" }]

[features]
default = ["stm32c092kc"]
# Select the MCU when building this crate.
stm32c092kc = ["embassy-stm32/stm32c092kc"]
stm32g0b1ce = ["embassy-stm32/stm32g0b1ce"]
# optionally enables bit rate switching in CAN tx
bit-rate-switching = []
# Local hw-test binary target for the STM32G0B1CE probe.
test = ["stm32g0b1ce"]

# Local hw-test binary target for the STM32G0B1CE probe.
# To run tests on device: cargo test --features test --target thumbv6m-none-eabi
[[bin]]
name = "hw-test"
path = "src/bin/test.rs"
harness = false
required-features = ["test"]

# [[bin]]
# name = "analog3"
# path = "src/main.rs"
# test = false
# bench = false

[lib]
path = "src/lib.rs"
test = false
bench = false
